### ISSUE TITLE
TCP stack stops responding after random amounts of time

### ISSUE THREAD

**Issue by quetric** [Xilinx/ACCL#11]
The TCP stack does not respond to requests after a random amount of time, ranging from 3s up to about 1 minute. This may be related to internal time-outs in the TCP stack

**Comment by DanieleParravicini** [comment]
Tried to determine failure time distribution:
                 x<5s        | xx
        5s   <x<10s      | xxx
        10s <x<15s      | 
        15s <x<20s      | x
        20s <x<25s      | 
        25s <x<30s      | xxxxx
        30s <x<35s      | xx
        35s <x<40s      | xxx
        40s <x<45s      | xx
                  x>45s       xxx
 
No clear pattern. Need to take a closer look to the stack
