### ISSUE TITLE
FPGABuffer class doesn't retrun physical hardware address after calling .bo() function

### ISSUE THREAD

**Issue by zhenhaohe** [Xilinx/ACCL#117]
The code below creates two fpga buffers and it is synced to device. However, the address got from the tx_buf_network->bo() and the rx_buf_network->bo() doesn't represent the physical FPGA memory address. So the network kernel can not write to memory, or can only write a very small amount of data to memory.

Buffer<int8_t> *tx_buf_network = new FPGABuffer<int8_t>(32*1024*1024, dataType::int8, device, networkmem);
Buffer<int8_t> *rx_buf_network = new FPGABuffer<int8_t>(32*1024*1024, dataType::int8,device, networkmem);
tx_buf_network->sync_to_device();
rx_buf_network->sync_to_device();
network_krnl(localFPGAIP, uint(rank), localFPGAIP, tx_buf_network->bo(), rx_buf_network->bo());

After changing the buffer instantiation using the original xrt api, it works fine. The code is attached below:

auto tx_buf_network = xrt::bo (device, 8*1024*1024*sizeof(int8_t), networkmem);
tx_buf_network.sync(XCL_BO_SYNC_BO_TO_DEVICE);
auto rx_buf_network = xrt::bo (device, 8*1024*1024*sizeof(int8_t), networkmem);
rx_buf_network.sync(XCL_BO_SYNC_BO_TO_DEVICE);
network_krnl(localFPGAIP, uint(rank), localFPGAIP, tx_buf_network, rx_buf_network);

**Comment by TristanLaan** [comment]
Hi Zhenhao, note that the [Buffer::bo](https://accl.readthedocs.io/en/latest/cpp_bindings/cpp_reference/buffer.html#_CPPv4N4ACCL10BaseBuffer2boEv) function returns a pointer to the bo object, not the bo object itself.

Could you try replacing
```C++
network_krnl(localFPGAIP, uint(rank), localFPGAIP, tx_buf_network->bo(), rx_buf_network->bo());
```
with
```C++
network_krnl(localFPGAIP, uint(rank), localFPGAIP, *(tx_buf_network->bo()), *(rx_buf_network->bo()));
```
and see if that works?

**Comment by Mellich** [comment]
`FPGABuffer::bo()` returns a pointer to `xrt::bo`. However, you need to pass a value to your kernel execution. Did you try something like:

```C++
network_krnl(localFPGAIP, uint(rank), localFPGAIP, *(tx_buf_network->bo()), *(rx_buf_network->bo()));
```
