### ISSUE TITLE
Performance issue with allgather, gather and scatter in large message size

### ISSUE THREAD

**Issue by zhenhaohe** [Xilinx/ACCL#118]
The performance of allgather, gather and scatter is worse than sw openmpi on large message size, which was not the case shown in the paper. See the attached performance plot below. 

![image](https://user-images.githubusercontent.com/31801294/198546694-71ebe2c7-bb6c-45a4-9d8f-b0307b33f4f0.png)
![image](https://user-images.githubusercontent.com/31801294/198546771-9c199249-7c20-416c-8d03-0a73f5d45559.png)
![image](https://user-images.githubusercontent.com/31801294/198546827-81d8e34f-61c5-4f25-bc07-3206b39c56ac.png)

**Comment by quetric** [comment]
@zhenhaohe how many ranks were used in this benchmark?

**Comment by quetric** [comment]
The latency charts are mostly on 4 ranks. Could you please post 4-rank charts as well?

**Comment by quetric** [comment]
Closing, this was found to be due to incorrect setting of count parameter in ACCL calls
