### ISSUE TITLE
Migrate to other ZMQ library for C++

### ISSUE THREAD

**Issue by TristanLaan** [Xilinx/ACCL#146]
We are currently using [zmqpp](https://github.com/zeromq/zmqpp) to interact with ZMQ from C++, but this project is no longer actively maintained and hasn't had a new release since [2017](https://github.com/zeromq/zmqpp/releases). Because of this, Ubuntu [no longer ships zmqpp since Ubuntu 22.04](https://packages.ubuntu.com/search?keywords=libzmqpp-dev).

We could consider migrating to [cppzmq](https://github.com/zeromq/cppzmq), which is a header-only library and doesn't need to be installed separately.

**Comment by quetric** [comment]
Done in #195
