### ISSUE TITLE
Unit Tests hang and fail on dev branch

### ISSUE THREAD

**Issue by Mellich** [Xilinx/ACCL#169]
Some of the unit tests hang in the dev branch for higher number of ranks (tested with 10):

- ACCLTest.test_alltoall
- ACCLTest.test_barrier
- ACCLTest.test_multicomm
- reduction_tests/ACCLFuncTest.test_allreduce/\*
- reduction_tests/ACCLFuncTest.test_allreduce_compressed/\*

Moreover, some other tests in ACCLFuncTest.* are failing.

**Comment by Mellich** [comment]
Fix failing tests in #170

**Comment by quetric** [comment]
Some tests hang for smaller number of ranks too, and different tests hang for different backends (UDP/TCP/RDMA). At least for alltoall and barrier, the cause is that the collective, as currently implemented in firmware, requires RDMA.
