### ISSUE TITLE
Error in Building hardware for Alveou280

### ISSUE THREAD

**Issue by sahmedbsc** [Xilinx/ACCL#186]
Hi,
I am trying to build the design for Alveou280 but getting the following error.

`ERROR: [HLS 207-812] 'ap_utils.h' file not found (/home/sahmed/ACCL/kernels/cclo/hls/eth_intf/../../../../driver/hls/./accl_hls.h:24:10)`

If someone could help me to localize this issue. right now i am using Vitis/Vivado 2023.2 version.

Thanks,

**Comment by Mellich** [comment]
I think the header `ap_utils.h` got moved in 2023.1. Try changing the includes to `etc/ap_utils.h` for example here: https://github.com/Xilinx/ACCL/blob/778f7d8c92aa837dc2d0e23ed988376ae0fcf822/driver/hls/accl_hls.h#L24

**Comment by sahmedbsc** [comment]
Thanks @Mellich, The above mentioned error is resolved.

Now i am getting platform related error. if you could help me with that. Do i need to install the required platform? if so from where i can install it.

``` 
ERROR: [v++ 60-1258] No valid platform was found that matches 'xilinx_u280_xdma_201920_3'. Please make sure that the platform is specified correctly, and the platform has the right version number. The platform repo paths are:
        /opt/Xilinx/Vitis/2023.2/platforms
The valid platforms found from the above repo paths are:

ERROR: [v++ 60-587] Failed to add a platform: specified platform xilinx_u280_xdma_201920_3 is not found or is not valid``

**Comment by Tobi-Alonso** [comment]
Hi @sahmedbsc , 
Yes, you need to have the target platform installed.

You should be able to setup your system following the "Getting Started" in: https://www.xilinx.com/products/boards-and-kits/alveo/u280.html

**Comment by quetric** [comment]
hi @sahmedbsc has this been resolved with the platform install?

**Comment by sahmedbsc** [comment]
Hi @quetric, 
The error i was getting is resolved and i am in process of installing the platform. for now we can close the issue.
